version: '3'
services:
    mssql:
      image: nuitsjp/adventureworks:latest
      container_name: source
      ports:
        - 1433:1433
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=P@ssw0rd!
    blank-mssql:
      image: nuitsjp/adventureworks:latest
      container_name: destination
      ports:
        - 1444:1433
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=P@ssw0rd!
